[common]
DATABASE_URL = "postgresql://andreas:Sierra16@localhost:5432/instagram"
INSTAGRAM_USERNAME = "afadesign.official"
INSTAGRAM_PASSWORD = "moKeiBSM&dL5CT8j"
#REDIS_URL = "jdbc:redis://localhost:6379/0"
CACHE_PREFIX = "followers:"

[default]
LOG_LEVEL = "INFO"  # Default log level

[development]
LOG_LEVEL = "DEBUG"  # Development log level

[testing]
LOG_LEVEL = "INFO"  # Testing log level

[production]
LOG_LEVEL = "ERROR"  # Production log level

[postgres]
# Common PostgreSQL configuration
USER = andreas
PASSWORD = Sierra16
HOST = localhost
PORT = 5432
DATABASE = instagram

[instagram]
# Common Instagram configuration
USERNAME = ${INSTAGRAM_USERNAME}
PASSWORD = ${INSTAGRAM_PASSWORD}

