# Generated by Django 5.0.3 on 2024-03-10 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proxy", models.CharField(blank=True, max_length=255)),
                ("settings", models.JSONField(default=dict)),
                ("delay_range", models.JSONField(blank=True)),
                ("logger", models.CharField(default="instagrapi", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InstagramClient",
            fields=[
                (
                    "client_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.client",
                    ),
                ),
            ],
            bases=("home.client",),
        ),
    ]
