# Generated by Django 5.0.3 on 2024-03-23 23:14

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagram_username",
                    models.CharField(
                        blank=True,
                        help_text="Instagram username of the user.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "instagram_password",
                    models.CharField(
                
