# Generated by Django 5.0.3 on 2023-03-27 00:44

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_client_instagramclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
