# Generated by Django 5.0.3 on 2024-03-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_client_instagramclient"),
        ("home", "0003_alter_userprofile_user"),
    ]

    operations = []
