# Generated by Django 5.0.3 on 2024-03-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalyticsData",
        ),
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.RemoveField(
            model_name="homeinstagramclient",
            name="client_ptr",
        ),
        migrations.DeleteModel(
            name="LogEntries",
        ),
        migrations.DeleteModel(
            name="PublicReportingData",
        ),
        migrations.DeleteModel(
            name="ReportingData",
        ),
        migrations.DeleteModel(
            name="HomeClient",
        ),
        migrations.DeleteModel(
            name="HomeInstagramclient",
        ),
    ]
