# This code imports the `PatchTypeAliases` class from the `mkdocstrings_patch_type_aliases._plugin` module.
# The purpose of this class is to patch type aliases in documentation generated by mkdocstrings.

from mkdocstrings_patch_type_aliases._plugin import PatchTypeAliases
