version: "3.8"

x-mount-app-and-user-git-config: &app-config
  volumes:
    - .:/app
    - ~/.gitconfig:/home/instagrapi/.gitconfig:ro

x-devbox-base: &devbox-base
  build:
    context: .
    dockerfile: "./docker/devbox.dockerfile"
    # Use buildx for multi-platform builds
    <<: *buildx-config
  networks:
    - app-network
  volumes: *app-config

services:
  devbox:
    <<: *devbox-base

  test:
    <<: *devbox-base
    command: "docker/run_tests.sh --format-code"

  tests:
    <<: *devbox-base
    command: "python -m unittest tests"

  lock-requirements:
    <<: *devbox-base
    entrypoint: "bash"
    command: "./docker/lock_requirements.sh"

  mkdocs:
    <<: *devbox-base
    image: "linuxserver/mkdocs:latest"
    ports:
      - "8000:8000"
    command: [ "serve", "--dev-addr=0.0.0.0:8000" ]

  mike:
    image: "linuxserver/mike:latest"
    entrypoint: "mike"

networks:
  app-network:
    driver: bridge

x-docker-buildx: &buildx-config
  builder:
    name: my-builder
    platforms:
      - linux/amd64
      - linux/arm64
