# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # Update Python packages with pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "auto"
    commit-message: "chore: Update ${package} to ${version}"
    update-schedule:
      day-of-month: "1-31"
      time: "03:00"

  # Update Docker images
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    versioning-strategy: "auto"
    commit-message: "chore: Update Docker image ${image}:${tag} to ${new_tag}"
    update-schedule:
      day-of-month: "1-31"
      time: "04:00"

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "auto"
    commit-message: "chore: Update GitHub Action ${action} to ${version}"
    update-schedule:
      day-of-month: "1-31"
      time: "05:00"
