#!/usr/bin/env bash

# Ensure that the script exits if any command fails
set -e

# Uninstall all packages that are currently installed
echo "Uninstalling currently installed packages..."
pip uninstall -y -r <(pip freeze)

# Install all packages from the requirements file
echo "Installing packages from requirements.txt..."
pip install -r requirements.txt

# Create a new lockfile with all installed packages
echo "Creating requirements.lock..."
printf "# THIS IS AN AUTOGENERATED LOCKFILE. DO NOT EDIT MANUALLY.\n" > requirements.lock
pip freeze --disable-pip-version-check --all >> requirements.lock

# Rebuild containers to verify that there are no conflicts
echo "Rebuild containers to verify there are no conflicts."
